### ISSUE TITLE
Не собирается проект: Unable to resolve symbol: gosuslugi-reg-form-webtest 

### ISSUE THREAD

**Issue by 3id010nCD** [seryh/example-selenium-project#5]
Здравствуйте! Не получается собрать ваш проект на линуксе:
```
Clojure/example-selenium-project >>> lein uberjar
 Compiling example-selenium-project.core
 java.lang.RuntimeException: Unable to resolve symbol: gosuslugi-reg-form-webtest in this context, compiling:(example_selenium_project/core.clj:15:3)
 Exception in thread "main" java.lang.RuntimeException: Unable to resolve symbol: gosuslugi-reg-form-webtest in this context, compiling:(example_selenium_project/core.clj:15:3)
     at clojure.lang.Compiler.analyze(Compiler.java:6688)
     at clojure.lang.Compiler.analyze(Compiler.java:6625)
     at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3766)
     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
     at clojure.lang.Compiler.analyze(Compiler.java:6669)
     at clojure.lang.Compiler.analyze(Compiler.java:6625)
     at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
     at clojure.lang.Compiler.analyze(Compiler.java:6669)
     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
     at clojure.lang.Compiler.analyze(Compiler.java:6669)
     at clojure.lang.Compiler.analyze(Compiler.java:6625)
     at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
     at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
     at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
     at clojure.lang.Compiler.analyze(Compiler.java:6669)
     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
     at clojure.lang.Compiler.analyze(Compiler.java:6669)
     at clojure.lang.Compiler.access$300(Compiler.java:38)
     at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
     at clojure.lang.Compiler.analyze(Compiler.java:6669)
     at clojure.lang.Compiler.analyze(Compiler.java:6625)
     at clojure.lang.Compiler.compile1(Compiler.java:7469)
     at clojure.lang.Compiler.compile(Compiler.java:7541)
     at clojure.lang.RT.compile(RT.java:406)
     at clojure.lang.RT.load(RT.java:451)
     at clojure.lang.RT.load(RT.java:419)
     at clojure.core$load$fn__5677.invoke(core.clj:5893)
     at clojure.core$load.invokeStatic(core.clj:5892)
     at clojure.core$load.doInvoke(core.clj:5876)
     at clojure.lang.RestFn.invoke(RestFn.java:408)
     at clojure.core$load_one.invokeStatic(core.clj:5697)
     at clojure.core$compile$fn__5682.invoke(core.clj:5903)
     at clojure.core$compile.invokeStatic(core.clj:5903)
     at clojure.core$compile.invoke(core.clj:5895)
     at user$eval20$fn__29.invoke(form-init752685504048807081.clj:1)
     at user$eval20.invokeStatic(form-init752685504048807081.clj:1)
     at user$eval20.invoke(form-init752685504048807081.clj:1)
     at clojure.lang.Compiler.eval(Compiler.java:6927)
     at clojure.lang.Compiler.eval(Compiler.java:6917)
     at clojure.lang.Compiler.eval(Compiler.java:6917)
     at clojure.lang.Compiler.load(Compiler.java:7379)
     at clojure.lang.Compiler.loadFile(Compiler.java:7317)
     at clojure.main$load_script.invokeStatic(main.clj:275)
     at clojure.main$init_opt.invokeStatic(main.clj:277)
     at clojure.main$init_opt.invoke(main.clj:277)
     at clojure.main$initialize.invokeStatic(main.clj:308)
     at clojure.main$null_opt.invokeStatic(main.clj:342)
     at clojure.main$null_opt.invoke(main.clj:339)
     at clojure.main$main.invokeStatic(main.clj:421)
     at clojure.main$main.doInvoke(main.clj:384)
     at clojure.lang.RestFn.invoke(RestFn.java:421)
     at clojure.lang.Var.invoke(Var.java:383)
     at clojure.lang.AFn.applyToHelper(AFn.java:156)
     at clojure.lang.Var.applyTo(Var.java:700)
     at clojure.main.main(main.java:37)
 Caused by: java.lang.RuntimeException: Unable to resolve symbol: gosuslugi-reg-form-webtest in this context
     at clojure.lang.Util.runtimeException(Util.java:221)
     at clojure.lang.Compiler.resolveIn(Compiler.java:7164)
     at clojure.lang.Compiler.resolve(Compiler.java:7108)
     at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7069)
     at clojure.lang.Compiler.analyze(Compiler.java:6648)
     ... 57 more
 Compilation failed: Subprocess failed (exit code: 1)
```

**Comment by seryh** [comment]
Здравствуйте. Я проверил, все работает. Судя по ошибке, у вас в файле gosuslugi_reg.clj не определен defwebtest gosuslugi-reg-form-webtest. Попробуйте склонировать проект в новую директорию и запустить lein uberjar
